### java stock
GET localhost:8080/api/v1/stock/save/java/1/50000

### database pessimistic lock stock
GET localhost:8080/api/v1/stock/save/database/pessimistic/1/50000

### database optimistic lock stock
GET localhost:8080/api/v1/stock/save/database/optimistic/1/50000

### database named lock stock
GET localhost:8080/api/v1/stock/save/database/named/1/50000

### redis incr lock stock
GET localhost:8080/api/v1/stock/save/redis/incr/1/50000

### redis lettuce lock stock
GET localhost:8080/api/v1/stock/save/redis/lettuce/1/50000

### redis redisson lock stock
GET localhost:8080/api/v1/stock/save/redis/redisson/1/10000

### kafka stock
GET localhost:8080/api/v1/stock/save/kafka/1/50000